#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xml-apis
Version  : 1.3.04
Release  : 3
URL      : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
Source0  : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
Source1  : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
Source2  : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.pom
Source3  : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
Source4  : https://repo1.maven.org/maven2/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-xml-apis-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-xml-apis package.
Group: Data

%description data
data components for the mvn-xml-apis package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.0.b2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.0.b2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01

mkdir -p %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.pom
/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
/usr/share/java/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.pom
/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar
/usr/share/java/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.pom
